spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/la_perruquera
spring.datasource.username=jorge
spring.datasource.password=MiClaveSuperSegura
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true